// dashboard.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
  standalone:false
})
export class DashboardComponent implements OnInit {
  emotionalStatus = 'SAD';
  sleepScore = 4;
  daysOfWeek = ['FR', 'SA', 'SU', 'MO', 'TU', 'WE', 'TH'];
  sleepData = [0.5, 0.3, 0.6, 0.4, 0.8, 0.2, 0.7]; // Values between 0-1 representing sleep quality
  
  trendItems = [
    {
      title: 'How to check your emotion',
      description: 'Understanding and managing your emotions is essential for maintaining mental well-being and making better decisions.',
      action: 'Get started',
      icon: 'emotions',
      imageSrc: './assets/BrainEmotions.png'
    },
    {
      title: 'How EEG works',
      description: 'It works by placing electrodes on the scalp, which detect tiny electrical signals generated by neurons as they communicate.',
      action: 'Get started',
      icon: 'brain',
      imageSrc: './assets/Emotions.png'
    }
  ];
  
  youtubeVideos = [
    { title: 'EEG Explained', thumbnail: './assets/EEG.jpeg' },
    { title: 'How EEG test works?', thumbnail: './assets/test.jpg' },
    { title: 'Getting an EEG', thumbnail: './assets/EEGS.png' }
  ];

  constructor() { }

  ngOnInit() {
    // Any initialization logic
  }

  navigateToDetails(item: any) {
    console.log('Navigating to details for:', item);
    // Add navigation logic here
  }

  navigateToVideo(video: any) {
    console.log('Navigating to video:', video);
    // Add navigation logic here
  }

  navigateToSleepDetails() {
    console.log('Navigating to sleep details');
    // Add navigation logic here
  }
}